### ISSUE TITLE
Add support for PHP 8.x, please

### ISSUE THREAD

**Issue by stevenmaguire** [thiagorb/codeship#1]
Great package - thank you for maintaining it!

I have a project that depends on this package. That project is currently upgrading to 8.x and that upgrade is blocked because this package's composer.json does not indicate it is compatible with PHP v 8.x.

  Problem 1
    - Root composer.json requires thiagorb/codeship ^0.4 -> satisfiable by thiagorb/codeship[0.4.0, 0.4.1].
    - thiagorb/codeship[0.4.0, ..., 0.4.1] require php ^7.1 -> your php version (8.0.20) does not satisfy that requirement.

Are you able to resolve that?

If the code is already compliant with PHP 8.x then the fix would be a simple update to your composer.json and a new release.

Something like this:

<img width="290" alt="CleanShot 2022-06-23 at 09 43 35@2x" src="https://user-images.githubusercontent.com/1851973/175327048-2ba48927-9f0f-4083-a9f4-248a118639b1.png">

**Comment by thiagorb** [comment]
Hello @stevenmaguire. I'll check if the code is compatible with PHP 8, and update the version.

**Comment by stevenmaguire** [comment]
@thiagorb thank you for the prompt response! It will be helpful!

**Comment by thiagorb** [comment]
@stevenmaguire can you please try using version 0.5.0?

**Comment by stevenmaguire** [comment]
@thiagorb back in action! Thank you!
